### ISSUE TITLE
Possible Addition: Emojicode

### ISSUE THREAD

**Issue by pennro-se** [dguo/jolly-code#4]
Hello there!

I love the idea you've had here, collecting all the less than serious but still great projects. There definitely are a few I haven't heard of before and seem quite interesting.

I have a suggestion for a possible addition: [Emojicode](https://www.emojicode.org/)

Emojicode is a full fledged, compiled, program language where the syntax is made up of emoji. I think that might qualify as Jolly.

As well, it's open source so I think that would be a bonus.

Thanks!

**Comment by dguo** [comment]
Glad you enjoyed the site, and thanks for the suggestion. I like it! I added it in https://github.com/dguo/jolly-code/commit/1e2d5771213cd182eb656fb586d39d1b4d085d9f.
